// Mirrors apps/backend/src/modules/users/demographics.constants.ts -- kept in
// sync manually since there's no shared package wired into the build yet.
export const MOTHER_TONGUE_LANGUAGES = [
  "Pashto",
  "Gojri",
  "Torwali",
  "Gawri",
  "Ushojo",
  "Kalkoti",
  "Palula",
  "Gawar-Bati",
  "Dameli",
  "Kalasha",
  "Kamviri",
  "Kativiri",
  "Khowar",
  "Wakhi",
  "Sarikoli",
  "Kyrgyz",
  "Yidgha",
  "Badeshi",
  "Indus Kohistani",
  "Ormuri",
  "Seraiki",
  "Tirahi",
  "Kohati",
  "Hindko (Peshawar, Kohat, Hazara)",
  "Sanglechi",
  "Chiliso",
  "Shina",
  "Pahari-Potohari",
  "Pashayi",
  "Persian",
  "Tajiki",
  "Balochi",
  "Brahui",
  "Nooristani",
  "Sindhi",
  "Parachi",
  "Uzbek",
] as const;

export const GENDER_OPTIONS: { value: "male" | "female" | "other" | "prefer_not_to_say"; label: string }[] = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
  { value: "prefer_not_to_say", label: "Prefer not to say" },
];

export const EDUCATION_LEVEL_OPTIONS: { value: "none" | "high_school" | "bachelors" | "masters" | "phd"; label: string }[] = [
  { value: "none", label: "None" },
  { value: "high_school", label: "High School" },
  { value: "bachelors", label: "Bachelors" },
  { value: "masters", label: "Masters" },
  { value: "phd", label: "PhD" },
];
